### ISSUE TITLE
Cannot compile for simulator or iPhone 5S

### ISSUE THREAD

**Issue by xaphod** [Vaberer/BlurTransition#1]
Downloaded master branch, tried to compile in xcode 6.4 for various iOS 8 flavors, I get this:

Ld /Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Products/Debug-iphoneos/BlurTransitionDemoTests.xctest/BlurTransitionDemoTests normal arm64
    cd /Users/Tim/temp/BlurTransition-master
    export IPHONEOS_DEPLOYMENT_TARGET=8.2
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -L/Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Products/Debug-iphoneos -F/Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/Developer/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/Developer/Library/Frameworks -filelist /Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Intermediates/BlurTransitionDemo.build/Debug-iphoneos/BlurTransitionDemoTests.build/Objects-normal/arm64/BlurTransitionDemoTests.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -bundle_loader /Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Products/Debug-iphoneos/BLUR.app/BLUR -framework XCTest -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=8.2 -Xlinker -dependency_info -Xlinker /Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Intermediates/BlurTransitionDemo.build/Debug-iphoneos/BlurTransitionDemoTests.build/Objects-normal/arm64/BlurTransitionDemoTests_dependency_info.dat -o /Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Products/Debug-iphoneos/BlurTransitionDemoTests.xctest/BlurTransitionDemoTests

ld: file not found: /Users/Tim/Library/Developer/Xcode/DerivedData/BlurTransitionDemo-fbfflobylpykyqamrtepqtbnpypu/Build/Products/Debug-iphoneos/BLUR.app/BLUR
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Vaberer** [comment]
Hello, I have just tried to clone a project and compile for iPhone 6 and simulators and it works perfectly. It seems you have something in your Xcode Derived Data, try to remove folder Derived Data: Xcode -> Preferences -> Locations.

**Comment by xaphod** [comment]
Hi Patrik

Thanks for your quick response.
Cleaning derived data was the first thing I tried, it still doesn't build
for me.
Did you try downloading master as zip file, extracting somewhere fresh, and
compiling? My guess is some project settings is wonky?
-tim

**Comment by xaphod** [comment]
... update, the problem appears to be that the build is looking for
BLUR.app, but in the folder I see BlurTransitionDemo.app

Project naming issue?

**Comment by Vaberer** [comment]
Actually, I renamed the project when I wanted to release it. But it still works for me, weird. You can pull a request with your change and maybe it will help other people:)

Thanks for opening and solving this issue :)
